### ISSUE TITLE
Shape Shift Minimum and Maximum

### ISSUE THREAD

**Issue by joebusby** [firebearstudio/shapeshift-magento2#1]
A few suggestions for the Shape Shift extension:

--  Add a min and max field to the configuration with the Shape Shift limits as the default and also the smallest and largest values that can be entered.   Then,  a checkbox to prevent the checkout option from being shown when the checkout total is outside the limits to prevent customer frustration in completing all the fields only to get the error from Shape Shift.

--  Add a description of what Shape Shift is on the payment type selection page, so people checking out will know it's for Crypto currency payment

--  Allow vendors to determine what payment options customers can use to make payments.  Some vendors may not want to support all types of currency, despite receiving all payments with the selected type.  Similar to selecting what countries they want to support.

--  The "return address" might need "(your receive address for any needed refunds)" or something similar added to the description so people don't put private keys in there.

Thanks for developing this extension.

**Comment by biotech** [comment]
Thank you @joebusby for feedback and suggestions  - we will implement all that on next release!

**Comment by biotech** [comment]
Hi @joebusby 

We are processing all points mentioned here except the last one. 
Can you elaborate point with "return address"? The current flow of refund is that customer should contact the merchant and provide wallet for the refund in progress of discussion about a refund, ShapeShift API don't have features for auto refund or some like that. Or you mean something else here?

Thanks for your assistance! Looking forward to more feedback!

**Comment by joebusby** [comment]
You seem to understand it correctly.

I was reacting to my initial confusion about what goes in the box.  It 
seems it's to be a public key if refunds are needed, so a simple change 
in the description might help others. Something like "Public key for 
refunds" or "Customer's public key for refunds"   It was just a thought 
I had.  Hope it helps.

**Comment by biotech** [comment]
Got it! Will be updated to "Return BTC wallet address (you will receive your funds back to this address in case of any issues or refund)"
Thanks for the contribution!

**Comment by biotech** [comment]
@joebusby we have released new version with all things implemented https://github.com/firebearstudio/shapeshift-magento2/releases/tag/v1.0.12

**Comment by joebusby** [comment]
Thanks!   Please let me know when it's updated for release, composer still shows 1.0.11 as the latest.

**Comment by biotech** [comment]
Updated https://github.com/firebearstudio/shapeshift-magento2/releases/tag/v1.0.12

**Comment by biotech** [comment]
Some lags with Packagist , will be fixed asap

**Comment by biotech** [comment]
Should works now https://packagist.org/packages/firebear/shapeshift 

Please let us know if you have any other issues or suggestions! Thanks for the contribution!
